IS_GPU: false
IS_TEST: true
IS_TRAIN: false
IS_VALID: true
MODEL: baseline
THEME: re_32
TYPE: 2
DATA:
  CHECK_HEATMAP: 5
  GAUSSIAN_SCALE: 1
  HEIGHT: 256
  WIDTH: 192
  IS_FLIP: false
  IS_INCRE: false
  IS_ROTATE: false
  IS_SCALE: false
  NUM_TOT_DATA: 32
  SIGMA: 2
  SAVE_RESIZED: true
  LARGE_HEATMAP: false
LOG:
  FILE_NAME: '%s_%s_log.txt'
  FREQ: 1
  PATH: result/%s/log
  SAVE_ACC: true
  SAVE_LOSS: true
PATH:
  BEST_FILE: '%s%d_best_model.pt'
  BEST_MODEL_PATH: best
  MODEL: baseline
  PRED_NAME: '%s_result_%d.json'
  PRED_PATH: prediction
TEST:
  BATCH_SIZE: 16
  FLIP_ENSEMBLE: false
  GET_RESULT: true
  IS_TEST: false
  MODEL_FILE: re_32_baseline32_best_model.pt
  MODEL_PATH: result/%s/best/
  SAVE_HEATMAP: 5
  SAVE_IMG_PER_BATCH: 10
  SAVE_PREDICTED: true
TRAIN:
  BATCH_SIZE: 16
  CHECK_FREQ: 20
  DECAY_RATE: 0.1
  EPOCH: 140
  IS_LOSS_MASK: true
  IS_SCHED: true
  IS_SHUFFLE: false
  LOAD_PREV: false
  LOSS: MSE
  LR: 0.0001
  MILTESTONES:
  - 90
  - 120
  OPTIM: Adam
  PREV_MODEL: new_heatmap_32_baseline32_best_model.pt
  PREV_PATH: '%s/best'
  SCHED: MultiStepLR
VAL:
  IS_TRAIN: false
  RES_FILE: 14
