IS_GPU: false
IS_TEST: false
IS_TRAIN: true
IS_VALID: false
MODEL: HRNet
THEME: HRNet_first_re
TYPE: 2
DATA:
  CHECK_HEATMAP: 0
  GAUSSIAN_SCALE: 1
  HEIGHT: 256
  WIDTH: 192
  IS_FLIP: false
  IS_INCRE: false
  IS_ROTATE: false
  IS_SCALE: false
  NUM_TOT_DATA: 32
  SIGMA: 2
  SAVE_RESIZED: false
  LARGE_HEATMAP: false
LOG:
  FILE_NAME: '%s_%s_log.txt'
  FREQ: 1
  PATH: result/%s/log
  SAVE_ACC: true
  SAVE_LOSS: true
PATH:
  BEST_FILE: '%s%d_best_model.pt'
  BEST_MODEL_PATH: best
  MODEL: HRNet
  PRED_NAME: '%s_result_%d.json'
  PRED_PATH: prediction
TEST:
  BATCH_SIZE: 16
  FLIP_ENSEMBLE: false
  GET_RESULT: true
  IS_TEST: false
  MODEL_FILE: HRNet_first_re_HRNet32_best_model.pt
  MODEL_PATH: result/%s/best/
  SAVE_HEATMAP: 0
  SAVE_IMG_PER_BATCH: 16
  SAVE_PREDICTED: true
TRAIN:
  BATCH_SIZE: 16
  CHECK_FREQ: 1000
  DECAY_RATE: 0.01
  EPOCH: 400
  IS_LOSS_MASK: true
  IS_SCHED: true
  IS_SHUFFLE: false
  LOAD_PREV: true
  LOAD_PREV_OPTIM: true
  LOAD_PREV_SCHED: true
  LOSS: MSE
  LR: 0.005
  MILTESTONES:
  - 350
  OPTIM: Adam
  PREV_MODEL: HRNet_first_re_HRNet32_best_model.pt
  PREV_PATH: '%s/best'
  SCHED: MultiStepLR
VAL:
  IS_TRAIN: false
  RES_FILE: 15
