DATA:
  GAUSSIAN_SCALE: 1
  HEIGHT: 192
  IMG_RATIO:
  - 3
  - 4
  INCRE_RATIO: 1.0
  IN_OUT_RATIO: 4
  IS_FLIP: false
  IS_INCRE: false
  IS_ROTATE: false
  IS_SCALE: false
  NUM_KEYS: 17
  NUM_TOT_DATA: 100
  ROTATE_RANGE:
  - -40
  - 40
  SAVE_RESIZED: true
  SCALE_RANGE:
  - 0.7
  - 1.3
  SIGMA: 2
  WIDTH: 256
  CHECK_HEATMAP: 5
IS_GPU: false
IS_TEST: true
IS_TRAIN: false
IS_VALID: false
LOG:
  FREQ: 1
  SAVE_ACC: true
  SAVE_LOSS: true
MODEL: 'baseline'
PATH:
  BEST_FILE: '%s%d_best_model.pt'
  BEST_MODEL_PATH: best
  CHECKPOINT_PATH: checkpoint
  CHECKPOINT_FILE: '%s%d_best_loss%f(%d_%d).pt'
  COCO_PATH: ./coco
  COCO_VAL_INS_PATH: annotations/instances_val2017.json
  COCO_VAL_KEY_PATH: annotations/person_keypoints_val2017.json
  MODEL: baseline
  PRED_NAME: '%s_result_%d.json'
  PRED_PATH: prediction
  RESIZED: resized
  RESULT_PATH: ./result
  SAMPLE: ./sample
TEST:
  BATCH_SIZE: 8
  FLIP_ENSEMBLE: false
  GET_RESULT: true
  IS_TEST: false
  MODEL_FILE: train_100_re_baseline100_best_model.pt
  MODEL_PATH: result/%s/best/
  SAVE_IMG_PER_BATCH: 2
  SAVE_PREDICTED: true
THEME: train_100_re
TRAIN:
  BATCH_SIZE: 32
  CHECK_FREQ: 20
  DECAY_RATE: 0.1
  EPOCH: 220
  IS_LOSS_MASK: true
  IS_SCHED: true
  IS_SHUFFLE: false
  LOAD_PREV: true
  LOSS: MSE
  LR: 0.00001
  MILTESTONES:
  - 170
  - 200
  OPTIM: Adam
  PREV_MODEL: train_100_baseline100_best_model.pt
  PREV_PATH: '%s/best'
  SCHED: MultiStepLR
TYPE: 2
VAL:
  IS_TRAIN: false
  RES_FILE: 3
